version: "3.9"  # optional since v1.27.0
services:
  semantic-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web-db-store.bdb:/app/web-db-store.bdb
      - ./userfile.txt:/app/userfile.txt
    environment:
      FLASK_DB_STORE_TYPE: SPARQLUpdateStore
      FLASK_DB_STORE_PATH: http://db-server:3030/semweb
    depends_on:
      - db-server
  reverse-proxy:
    build: ./nginx
    ports:
      - "8080:443"
    environment:
      NGINX_HOSTNAME: semweb.localhost
    volumes:
      - ./certs/cert.pem:/certs/cert.pem
      - ./certs/key.pem:/certs/key.pem
    depends_on:
      - semantic-app
  db-server:
    build: ./jena-fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./jenadb/:/app/db
    #command: ["./apache-jena-fuseki-4.5.0/fuseki-server","--help"]
