version: "3.9"  # optional since v1.27.0
services:
  semantic-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web-db-store.bdb:/app/web-db-store.bdb
      - ./userfile.txt:/app/userfile.txt
    environment:
      FLASK_DB_STORE_TYPE: SPARQLUpdateStore
      FLASK_DB_STORE_PATH: http://db-server:3030/semweb
    depends_on:
      - db-server
  reverse-proxy:
    build: ./nginx
    ports:
      - "8080:443"
    environment:
      NGINX_HOSTNAME: semweb.localhost
    volumes:
      - ./certs/:/certs/
    depends_on:
      - semantic-app
  db-server:
    image: ghcr.io/jhugon/apache-jena-fuseki-docker:main
    ports:
      - "3030:3030"
    volumes:
      - jenadb:/fuseki/databases
    command: ["--update","--loc=/fuseki/databases","/semweb"]
volumes:
  jenadb:
