version: "3.9"  # optional since v1.27.0
services:
  semantic-app:
    image: ghcr.io/jhugon/semantic-data-taking-webapp:latest
    ports:
      - "8000:8000"
    volumes:
      - users:/app/users
    environment:
      FLASK_DB_STORE_TYPE: SPARQLUpdateStore
      FLASK_DB_STORE_PATH: http://db-server:3030/semweb
      FLASK_SERVER_NAME: semweb.localhost
      FLASK_LOGIN_USER_FILE_PATH: /app/users/userfile.txt
    depends_on:
      - db-server
  reverse-proxy:
    build: ./nginx
    ports:
      - "8080:443"
    environment:
      NGINX_HOSTNAME: semweb.localhost
    volumes:
      - ./certs/:/certs/
    depends_on:
      - semantic-app
  db-server:
    image: ghcr.io/jhugon/apache-jena-fuseki-docker:main
    ports:
      - "3030:3030"
    volumes:
      - jenadb:/fuseki/databases
    #environment:
    #  - "JAVA_OPTIONS=-Xmx512m -Xms512m"
    command: ["--update","--loc=/fuseki/databases","/semweb"]
volumes:
  jenadb:
  users:
