version: "3.9"  # optional since v1.27.0
services:
  semantic-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./web-db-store.bdb:/app/web-db-store.bdb
      - ./userfile.txt:/app/userfile.txt
