version: "3.9"  # optional since v1.27.0
services:
  semantic-app:
    build: .
    volumes:
      - ./web-db-store.bdb:/app/web-db-store.bdb
      - ./userfile.txt:/app/userfile.txt
    #ports:
    #  - "8000:8000"
  reverse-proxy:
    build: ./nginx
    ports:
      - "8080:80"
