version: "3.9"  # optional since v1.27.0
services:
  semantic-app:
    build: .
    volumes:
      - ./web-db-store.bdb:/app/web-db-store.bdb
      - ./userfile.txt:/app/userfile.txt
  reverse-proxy:
    build: ./nginx
    ports:
      - "8080:80"
    environment:
      NGINX_HOSTNAME: semweb.localhost
  db-server:
    build: ./jena-fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./jenadb/:/app/db
    #command: ["./apache-jena-fuseki-4.5.0/fuseki-server","--help"]
