# .github/workflows/ci.yml

name: Uplift
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # present by default
      GITHUB_TOKEN: ${{ secrets.GH_UPLIFT }} # allows tag to spawn new workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #
      # Additional steps specified here
      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: gembaadvantage/uplift-action@v2.0.1
        with:
          args: release
